#!/usr/bin/env python3
"""Regenerates source/credit_font.h, the small proportional face the top screen is labelled with.

Both bottom corners of the top screen are drawn at runtime: the version on the left, the credit on
the right. Neither is painted into graphics/logo.png any more, so a version bump never means
re-exporting artwork, and both labels are guaranteed to be the same face.

Coverage stays antialiased. At a seven pixel cap height, thresholding leaves the narrow lowercase
('x' and 'a' especially) as unreadable blobs, and the shapes need the intermediate coverage to read
at all.

Advances are measured at SUB times the render size and stored in 1/SUBths of a pixel. Helvetica's
advances here are fractional ('i' is 2.25px, 'T' is 6.125px); rounding each to a whole pixel on its
own leaves the error in the gap after that letter, which is what makes the spacing look uneven.

Run from TwilightBoxart.DSi/ with ImageMagick installed:

    python3 tools/genfont.py
"""

import subprocess
import sys

FONT = "/System/Library/Fonts/Helvetica.ttc"
PS = 10                    # render size, in points
SUB = 16                   # advances are kept in 1/16th of a pixel
CELL_W, CELL_H = 12, 12
BASELINE = 9               # baseline row within a cell

# ASCII, plus the copyright sign the credit needs. The table is indexed by codepoint, so the
# unused stretch between them costs a handful of empty entries and no glyph data at all.
CODEPOINTS = list(range(32, 127)) + [0xA9]
FIRST, LAST = CODEPOINTS[0], CODEPOINTS[-1]
COUNT = LAST - FIRST + 1

OUT = "source/credit_font.h"


def width(text, pointsize):
    """Rendered advance width of a string. Antialiased: these are the font's real metrics."""
    text = text.replace("%", "%%")
    r = subprocess.run(
        ["magick", "-background", "none", "-font", FONT, "-pointsize", str(pointsize),
         f"label:{text}", "-format", "%w", "info:"],
        capture_output=True, text=True)
    return int(r.stdout.strip() or 0)


def measure_advances():
    """Advance per codepoint, in 1/SUBths of a pixel.

    Measured as the growth of "HcH" over "HH" rather than the width of the glyph on its own, so the
    number carries both side bearings exactly as the font intends them.
    """
    base = width("HH", PS * SUB)
    return {c: width("H" + chr(c) + "H", PS * SUB) - base for c in CODEPOINTS}


def render_atlas():
    """Every glyph drawn once, pen origin at x = i * CELL_W with the baseline at BASELINE."""
    args = ["magick", "-size", f"{len(CODEPOINTS) * CELL_W}x{CELL_H}", "xc:none",
            "-font", FONT, "-pointsize", str(PS), "-fill", "white"]
    for i, c in enumerate(CODEPOINTS):
        args += ["-annotate", f"+{i * CELL_W}+{BASELINE}", chr(c)]
    args += ["/tmp/credit_atlas.png"]
    subprocess.run(args, check=True)

    pgm = subprocess.run(["magick", "/tmp/credit_atlas.png", "-alpha", "extract",
                          "-depth", "8", "pgm:-"], capture_output=True).stdout
    head = pgm.split(b"\n", 3)
    assert head[0].strip() == b"P5", head[0]
    w, h = map(int, head[1].split())
    return w, h, pgm[-w * h:]


def main():
    advances = measure_advances()
    w, h, pixels = render_atlas()

    def at(x, y):
        return pixels[y * w + x] if 0 <= x < w and 0 <= y < h else 0

    glyphs = {}
    blob = []
    for i, c in enumerate(CODEPOINTS):
        x0 = i * CELL_W
        ink = [(xx, yy) for yy in range(CELL_H) for xx in range(CELL_W) if at(x0 + xx, yy) > 8]
        if not ink:
            glyphs[c] = (advances[c], 0, 0, 0, 0, 0)
            continue
        minx = min(x for x, _ in ink); maxx = max(x for x, _ in ink)
        miny = min(y for _, y in ink); maxy = max(y for _, y in ink)
        gw, gh = maxx - minx + 1, maxy - miny + 1
        glyphs[c] = (advances[c], gw, gh, minx, miny, len(blob))
        blob += [at(x0 + minx + xx, miny + yy) for yy in range(gh) for xx in range(gw)]

    lines = [
        f"// Generated by tools/genfont.py. Helvetica {PS}pt, antialiased coverage per pixel.",
        "// Codepoints 32..126 plus 0xA9, the copyright sign; the gap between them is empty entries.",
        "",
        f"#define CREDIT_FONT_FIRST    {FIRST}",
        f"#define CREDIT_FONT_COUNT    {COUNT}",
        f"#define CREDIT_FONT_BASELINE {BASELINE}",
        f"#define CREDIT_FONT_SUB      {SUB}",
        "",
        "typedef struct {",
        "    u16 advance;   /* 1/16th of a pixel */",
        "    u8 w, h, xoff, yoff;",
        "    u16 offset;    /* into credit_font_alpha */",
        "} CreditGlyph;",
        "",
        "static const CreditGlyph credit_font[CREDIT_FONT_COUNT] = {",
    ]
    for c in range(FIRST, LAST + 1):
        a, gw, gh, xo, yo, off = glyphs.get(c, (0, 0, 0, 0, 0, 0))
        label = repr(chr(c)) if c in glyphs else "unused"
        lines.append(f"    {{ {a:4d}, {gw:2d}, {gh:2d}, {xo:2d}, {yo:2d}, {off:5d} }}, /* {label} */")
    lines.append("};")
    lines.append("")
    lines.append(f"static const u8 credit_font_alpha[{len(blob)}] = {{")
    for i in range(0, len(blob), 16):
        lines.append("    " + ",".join(f"{v:3d}" for v in blob[i:i + 16]) + ",")
    lines.append("};")

    open(OUT, "w").write("\n".join(lines) + "\n")
    print(f"{OUT}: {len(CODEPOINTS)} glyphs, {len(blob)} coverage bytes", file=sys.stderr)


main()
